# infrastructure/ansible/inventory/hosts.yml
all:
  hosts:
    cocktaildb:
      ansible_host: "{{ lookup('env', 'COCKTAILDB_HOST') }}"
      ansible_user: ec2-user
  vars:
    ansible_python_interpreter: /usr/bin/python3
